title: Tristan Misko
author:
  name: Tristan Misko
  email: tristanmisko@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  Tristan Misko's portfolio website and personal blog.

show_excerpts: false # set to true to show excerpts on the homepage



collections:
  - projects
  - about
  - pages

collections:
  about:
    output: true
  projects:
    output: true
  pages:
    output: true

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"


  # generate social links in footer
  social_links:
    #twitter: jekyllrb
    github:  tjmisko
    # devto: jekyll
    # dribbble: jekyll
    facebook: tristanmisko
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: tristan-misko
    spotify: tristanmisko
    # pinterest: jekyll
    # youtube: "\\@tjmisko"
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: tjmisko
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
markdown: kramdown

plugins:
 - jekyll-feed
 - jekyll-seo-tag
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
