title: Tristan Misko
author: Tristan Misko
  name: tjmisko
  email: tristanmisko@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  I work with data and code to understand systems, solve problems, and build
  things. Welcome to my website! You can keep scrolling to learn a bit more
  about me, view my portfolio, read my blog, and contact me. I am actively
  looking for new work opportunities right now. Reach out at the links below
  if you are interested in working with me! 


show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"


  # generate social links in footer
  social_links:
    #twitter: jekyllrb
    github:  tjmisko
    # devto: jekyll
    # dribbble: jekyll
    facebook: tristanmisko
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: tjmisko
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
markdown: kramdown

plugins:
 - jekyll-feed
 - jekyll-seo-tag
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
